# Generated by Django 3.2.5 on 2023-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('MemID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='會員編號')),
                ('Memsanfan', models.CharField(max_length=100, verbose_name='會員身分證')),
                ('Serv', models.CharField(max_length=100, verbose_name='服務項目')),
                ('SCarbon', models.IntegerField(verbose_name='碳排量')),
                ('SPoint', models.IntegerField(verbose_name='消費點數')),
                ('SDATE', models.DateTimeField()),
            ],
        ),
    ]
