# Generated by Django 3.2.5 on 2023-01-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='MemID',
        ),
        migrations.AddField(
            model_name='order',
            name='OID',
            field=models.CharField(default=1, max_length=1000, primary_key=True, serialize=False, verbose_name='訂單編號'),
            preserve_default=False,
        ),
    ]
