# Generated by Django 3.2.5 on 2023-01-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_ocmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='point',
            fields=[
                ('PID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='點數兌換編號')),
                ('Memsanfan', models.CharField(max_length=100, verbose_name='會員身分證')),
                ('PChange', models.CharField(max_length=100, verbose_name='增減')),
                ('PPS', models.CharField(max_length=100, verbose_name='說明')),
                ('PPoint', models.IntegerField(verbose_name='點數')),
                ('PCmp', models.CharField(max_length=100, verbose_name='合作廠商')),
                ('PDATE', models.DateTimeField()),
            ],
        ),
    ]
