# Generated by Django 3.2.5 on 2023-01-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanged',
            fields=[
                ('EID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='點數兌換編號')),
                ('Memsanfan', models.CharField(max_length=100, verbose_name='會員身分證')),
                ('Ename', models.CharField(max_length=100, verbose_name='服務')),
                ('EPS', models.CharField(max_length=100, verbose_name='說明')),
                ('EPoint', models.IntegerField(verbose_name='點數')),
                ('ECmp', models.CharField(max_length=100, verbose_name='合作廠商')),
                ('EDDline', models.CharField(max_length=100, verbose_name='剩餘期限')),
                ('EDATE', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('SID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='點數兌換編號')),
                ('Memsanfan', models.CharField(max_length=100, verbose_name='會員身分證')),
                ('Sname', models.CharField(max_length=100, verbose_name='服務')),
                ('SPS', models.CharField(max_length=100, verbose_name='說明')),
                ('SPoint', models.IntegerField(verbose_name='點數')),
                ('SCmp', models.CharField(max_length=100, verbose_name='合作廠商')),
            ],
        ),
        migrations.AlterField(
            model_name='point',
            name='PID',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='點數變更編號'),
        ),
    ]
