# Generated by Django 3.2.5 on 2023-01-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230106_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='SID',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='服務編號'),
        ),
    ]
