# Generated by Django 3.2.5 on 2023-01-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_service_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Memsanfan',
        ),
    ]
