# Generated by Django 3.2.5 on 2023-01-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_service_memsanfan'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='SKind',
            field=models.CharField(default=1, max_length=100, verbose_name='服務分類'),
            preserve_default=False,
        ),
    ]
