# Generated by Django 3.2.5 on 2023-01-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_service_skind'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='SDDline',
            field=models.CharField(default=1, max_length=100, verbose_name='使用期限'),
            preserve_default=False,
        ),
    ]
