# Generated by Django 3.2.5 on 2023-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanged',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='MCarbon',
            field=models.IntegerField(null=True, verbose_name='碳排量'),
        ),
        migrations.AlterField(
            model_name='exchanged',
            name='EID',
            field=models.CharField(max_length=1000, verbose_name='點數兌換編號'),
        ),
    ]
