# Generated by Django 3.2.5 on 2023-01-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230107_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='PID',
            field=models.CharField(max_length=1000, verbose_name='點數變更編號'),
        ),
    ]
