# Generated by Django 3.2.5 on 2023-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230107_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='MemPic',
            field=models.CharField(max_length=100, null=True, verbose_name='頭貼'),
        ),
    ]
