# Generated by Django 3.2.5 on 2023-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_member_mempic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID', models.CharField(max_length=1000, verbose_name='服務編號')),
                ('Vname', models.CharField(max_length=100, verbose_name='服務')),
                ('VCarbon', models.IntegerField(verbose_name='碳排')),
                ('SCmp', models.CharField(max_length=100, verbose_name='合作廠商')),
            ],
        ),
    ]
