# Generated by Django 3.2.5 on 2023-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='SCmp',
            new_name='VCmp',
        ),
    ]
