# Generated by Django 3.2.5 on 2023-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_scmp_volunteer_vcmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MCarbon',
            field=models.FloatField(null=True, verbose_name='碳排量'),
        ),
    ]
