# Generated by Django 3.2.5 on 2023-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_member_memcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MemCity',
            field=models.CharField(max_length=100, verbose_name='會員城市'),
        ),
    ]
