# Generated by Django 3.2.5 on 2023-01-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_member_memcity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
