# Generated by Django 3.2.5 on 2023-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='SCarbon',
            field=models.IntegerField(default=1, verbose_name='碳排量'),
            preserve_default=False,
        ),
    ]
