# Generated by Django 3.2.5 on 2023-01-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_service_scarbon'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanged',
            name='ECarbon',
            field=models.IntegerField(default=1, verbose_name='碳排量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='PCarbon',
            field=models.IntegerField(default=1, verbose_name='碳排量'),
            preserve_default=False,
        ),
    ]
