# Generated by Django 3.2.5 on 2023-01-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20230113_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='VChrck',
            field=models.BooleanField(default=1, verbose_name='完成確認'),
            preserve_default=False,
        ),
    ]
