# Generated by Django 3.2.5 on 2023-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_member_memrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='MemRPic',
            field=models.CharField(max_length=100, null=True, verbose_name='徽章'),
        ),
    ]
