# Generated by Django 3.2.5 on 2023-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_member_memrpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID', models.CharField(max_length=1000, verbose_name='任務編號')),
                ('Vname', models.CharField(max_length=100, verbose_name='任務')),
                ('VCarbon', models.IntegerField(verbose_name='碳排')),
                ('VCheck', models.BooleanField(verbose_name='完成確認')),
            ],
        ),
    ]
