# Generated by Django 3.2.5 on 2023-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanged',
            name='ECarbon',
            field=models.FloatField(verbose_name='碳排量'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='VCarbon',
            field=models.FloatField(verbose_name='碳排'),
        ),
        migrations.AlterField(
            model_name='order',
            name='SCarbon',
            field=models.FloatField(verbose_name='碳排量'),
        ),
        migrations.AlterField(
            model_name='point',
            name='PCarbon',
            field=models.FloatField(verbose_name='碳排量'),
        ),
        migrations.AlterField(
            model_name='service',
            name='SCarbon',
            field=models.FloatField(verbose_name='碳排量'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='VCarbon',
            field=models.FloatField(verbose_name='碳排'),
        ),
    ]
