# Generated by Django 3.2.5 on 2023-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20230114_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Memxin',
            field=models.CharField(max_length=100, null=True, verbose_name='會員信用卡號'),
        ),
    ]
